import pg from "pg";
import type { World } from "./generator.js";
import { databaseUrl, urlForDatabase } from "./db.js";

export const TEMPLATE_DB = "gatehouse_seed";

/** Fake bearer tokens. They only mean something to the mock systems in this repo. */
export const SERVICE_TOKENS = { crm: "crm-service-token", tickets: "tickets-service-token" } as const;
export const userToken = (system: "crm" | "tickets", userId: number) => `${system}-user-${userId}`;
export const personaToken = (personId: number) => `person-${personId}`;

const SCHEMA = `
create schema crm;
create schema tickets;
create schema gateway;

create table crm.users (
  id int primary key, person_id int not null, name text not null, email text not null,
  role text not null, region text, manager_id int references crm.users(id)
);
create table crm.api_tokens (token text primary key, user_id int references crm.users(id));
create table crm.accounts (
  id int generated by default as identity (start with 100000) primary key,
  name text not null, region text not null, owner_id int not null references crm.users(id), industry text not null
);
create table crm.contacts (
  id int generated by default as identity (start with 100000) primary key,
  account_id int not null references crm.accounts(id), name text not null, email text not null,
  title text not null, region text not null, owner_id int not null references crm.users(id)
);
create table crm.opportunities (
  id int generated by default as identity (start with 100000) primary key,
  account_id int not null references crm.accounts(id), name text not null, region text not null,
  owner_id int not null references crm.users(id), stage text not null, amount int not null,
  discount_floor numeric(5,4) not null, close_quarter text not null
);
create table crm.activities (
  id int generated by default as identity (start with 100000) primary key,
  opportunity_id int not null references crm.opportunities(id), subject text not null, kind text not null,
  region text not null, owner_id int not null references crm.users(id)
);

create table tickets.users (id int primary key, person_id int not null, name text not null, email text not null);
create table tickets.api_tokens (token text primary key, user_id int references tickets.users(id));
create table tickets.projects (id int primary key, key text not null unique, name text not null);
create table tickets.project_members (
  project_id int not null references tickets.projects(id), user_id int not null references tickets.users(id),
  primary key (project_id, user_id)
);
create table tickets.tickets (
  id int generated by default as identity (start with 100000) primary key,
  project_id int not null references tickets.projects(id), title text not null, body text not null,
  status text not null, priority text not null, reporter_id int not null references tickets.users(id)
);
create table tickets.comments (
  id int generated by default as identity (start with 100000) primary key,
  ticket_id int not null references tickets.tickets(id), author_id int not null references tickets.users(id),
  body text not null
);

-- Every upstream write, from either system. approval_id is set only when the
-- approval executor presents the executor secret.
create table public.write_log (
  id int generated always as identity primary key,
  system text not null, entity text not null, record_id int, action text not null,
  data jsonb not null, actor_user_id int, approval_id int
);

-- Gateway state.
create table gateway.identities (
  person_id int not null, system text not null, user_id int not null, token text not null,
  primary key (person_id, system)
);
create table gateway.groups (person_id int not null, name text not null, primary key (person_id, name));
create table gateway.approvals (
  id int generated always as identity primary key,
  idem_key text not null, status text not null, bundle text not null,
  requester_person_id int not null, approver_person_id int,
  system text not null, tool text not null, args jsonb not null, result jsonb
);
create unique index approvals_pending_key on gateway.approvals (idem_key) where status = 'pending';
create table gateway.audit_log (
  id int generated always as identity primary key,
  person_id int, bundle text not null, tool text not null, mode text not null,
  params_before jsonb not null, params_after jsonb not null, decision text not null,
  reasons jsonb not null, item_count int, approval_id int, latency_ms double precision not null
);
`;

async function insertRows(client: pg.ClientBase, table: string, rows: Record<string, unknown>[]): Promise<void> {
  if (rows.length === 0) return;
  const cols = Object.keys(rows[0]!);
  for (let i = 0; i < rows.length; i += 200) {
    const chunk = rows.slice(i, i + 200);
    const params: unknown[] = [];
    const values = chunk.map((row) => `(${cols.map((c) => { params.push(row[c]); return `$${params.length}`; }).join(",")})`);
    await client.query(`insert into ${table} (${cols.join(",")}) overriding system value values ${values.join(",")}`, params);
  }
}

export async function seedDatabase(client: pg.ClientBase, world: World): Promise<void> {
  await client.query(SCHEMA);
  const ordered = [...world.people].sort((a, b) => (a.crmManagerId ?? 0) - (b.crmManagerId ?? 0) || a.id - b.id);
  await insertRows(client, "crm.users", ordered.map((p) => ({
    id: p.crmUserId, person_id: p.id, name: p.name, email: p.email, role: p.crmRole, region: p.region, manager_id: p.crmManagerId,
  })));
  await insertRows(client, "tickets.users", [
    { id: 9000, person_id: 0, name: "Integration service", email: "integration@example.test" },
    ...world.people.map((p) => ({ id: p.ticketsUserId, person_id: p.id, name: p.name, email: p.email })),
  ]);
  await insertRows(client, "crm.api_tokens", [
    { token: SERVICE_TOKENS.crm, user_id: null },
    ...world.people.map((p) => ({ token: userToken("crm", p.crmUserId), user_id: p.crmUserId })),
  ]);
  await insertRows(client, "tickets.api_tokens", [
    { token: SERVICE_TOKENS.tickets, user_id: null },
    ...world.people.map((p) => ({ token: userToken("tickets", p.ticketsUserId), user_id: p.ticketsUserId })),
  ]);
  await insertRows(client, "crm.accounts", world.crm.accounts as unknown as Record<string, unknown>[]);
  await insertRows(client, "crm.contacts", world.crm.contacts as unknown as Record<string, unknown>[]);
  await insertRows(client, "crm.opportunities", world.crm.opportunities as unknown as Record<string, unknown>[]);
  await insertRows(client, "crm.activities", world.crm.activities as unknown as Record<string, unknown>[]);
  await insertRows(client, "tickets.projects", world.tickets.projects as unknown as Record<string, unknown>[]);
  await insertRows(client, "tickets.project_members", world.tickets.members);
  await insertRows(client, "tickets.tickets", world.tickets.tickets as unknown as Record<string, unknown>[]);
  await insertRows(client, "tickets.comments", world.tickets.comments as unknown as Record<string, unknown>[]);
  await insertRows(client, "gateway.groups", Object.entries(world.groups).flatMap(([name, ids]) => ids.map((person_id) => ({ person_id, name }))));
  await insertRows(client, "gateway.identities", world.people.flatMap((p) => [
    { person_id: p.id, system: "crm", user_id: p.crmUserId, token: userToken("crm", p.crmUserId) },
    { person_id: p.id, system: "tickets", user_id: p.ticketsUserId, token: userToken("tickets", p.ticketsUserId) },
  ]));
}

async function withMaintenance<T>(fn: (c: pg.Client) => Promise<T>, base = databaseUrl()): Promise<T> {
  const c = new pg.Client({ connectionString: urlForDatabase("postgres", base) });
  await c.connect();
  try {
    return await fn(c);
  } finally {
    await c.end();
  }
}

/** Builds the seed template. Closes its own connection, so nothing stays attached to the template. */
export async function createTemplate(world: World, base = databaseUrl()): Promise<void> {
  await withMaintenance(async (c) => {
    await c.query(`drop database if exists ${TEMPLATE_DB} with (force)`);
    await c.query(`create database ${TEMPLATE_DB}`);
  }, base);
  const c = new pg.Client({ connectionString: urlForDatabase(TEMPLATE_DB, base) });
  await c.connect();
  try {
    await c.query("begin");
    await seedDatabase(c, world);
    await c.query("commit");
  } finally {
    await c.end();
  }
}

/** Fresh copy of the template for one run. Returns its connection string. */
export async function createRunDb(name: string, base = databaseUrl()): Promise<string> {
  if (!/^[a-z0-9_]+$/.test(name)) throw new Error(`bad database name ${name}`);
  await withMaintenance(async (c) => {
    await c.query(`drop database if exists ${name} with (force)`);
    await c.query(`create database ${name} template ${TEMPLATE_DB}`);
  }, base);
  return urlForDatabase(name, base);
}

export async function dropRunDb(name: string, base = databaseUrl()): Promise<void> {
  await withMaintenance((c) => c.query(`drop database if exists ${name} with (force)`).then(() => undefined), base);
}

export async function templateExists(base = databaseUrl()): Promise<boolean> {
  return withMaintenance(async (c) => (await c.query("select 1 from pg_database where datname = $1", [TEMPLATE_DB])).rowCount === 1, base);
}

/** Seeds a brand new database directly (not from the template). Used by the determinism test. */
export async function seedFresh(name: string, world: World, base = databaseUrl()): Promise<string> {
  if (!/^[a-z0-9_]+$/.test(name)) throw new Error(`bad database name ${name}`);
  await withMaintenance(async (c) => {
    await c.query(`drop database if exists ${name} with (force)`);
    await c.query(`create database ${name}`);
  }, base);
  const url = urlForDatabase(name, base);
  const c = new pg.Client({ connectionString: url });
  await c.connect();
  try {
    await seedDatabase(c, world);
  } finally {
    await c.end();
  }
  return url;
}
